- hosts: 127.0.0.1

  vars_prompt:
    - name: ikim_username
      prompt: What is your IKIM username?
      private: false

  tasks:
    # taken from https://github.com/gantsign/ansible-role-visual-studio-code
    - name: Install VS Code repo
      become: yes
      yum_repository:
        name: code
        description: Visual Studio Code repo
        file: vscode
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: yes

    - name: Enable Fedora Coprs
      become: yes
      community.general.copr:
        name: "{{ item }}"
      loop:
        - atim/starship
        - atim/nushell
    
    - name: Importing RPM Fusion keys
      become: yes
      rpm_key:
        state: present
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-{{ item }}-fedora-2020"
      loop:
        - free
        - nonfree

    - name: Enable the RPM Fusion repository
      become: yes
      package:
        name:
          - "https://mirrors.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      loop:
        - free
        - nonfree

    - name: Install packages
      become: yes
      package:
        name:
          - code
          - rust
          - cargo
          - git
          - cmake
          - nushell
          - util-linux-user
          - discord
          - starship
          - google-noto-sans-fonts
          - google-noto-sans-mono-fonts
          - google-noto-serif-fonts
          - google-noto-emoji-fonts
          - "@Development Tools"

    - name: Install vcode extensions
      command: "code --install-extension {{ item }}"
      loop:
        - tfehlmann.snakefmt
        - Snakemake.snakemake-lang
        - ms-vscode-remote.remote-ssh
        - rust-lang.rust-analyzer
        - mechatroner.rainbow-csv
        - GitHub.copilot
        - GitHub.vscode-pull-request-github
        - GitHub.remotehub

    - name: Setup SSH
      copy:
        dest: ~/.ssh/config
        content: |
          Host *
            AddKeysToAgent yes
            CanonicalizeHostname yes

          Host ikim
            HostName login.ikim.uk-essen.de
            User {{ ikim_username }}}
            IdentityFile ~/.ssh/id_ikim
            ForwardAgent yes

          Host g1-? c? c?? shellhost
            Hostname %h.ikim.uk-essen.de
            User {{ ikim_username }}}
            IdentityFile ~/.ssh/id_ikim
            ProxyJump ikim
            ForwardAgent yes

    - name: Setup shell functions and aliases
      copy:
        dest: ~/.profile
        content: |
          alias ikim-proxy="ssh -fND 7001 ikim"

    - name: Setup starship
      lineinfile:
        dest: ~/.bashrc
        line: 'eval "$(starship init bash)"'

    - name: Register nushell
      become: yes
      lineinfile:
        dest: /etc/shells
        line: /usr/bin/nu

    # - name: Setup nushell as default
    #   become: yes
    #   command: "chsh -s /usr/bin/nu {{ ansible_user_id }}"