- name: Setup SSH
  copy:
    dest: ~/.ssh/config
    content: |
      Host *
        AddKeysToAgent yes
        CanonicalizeHostname yes

      Host ikim
        HostName login.ikim.uk-essen.de
        User {{ ikim_username }}
        IdentityFile ~/.ssh/{{ ikim_ssh_key }}
        ForwardAgent yes

      Host g1-? c? c?? shellhost
        Hostname %h.ikim.uk-essen.de
        User {{ ikim_username }}
        IdentityFile ~/.ssh/{{ ikim_ssh_key }}
        ProxyJump ikim
        ForwardAgent yes
      
      Host github.com
        IdentityFile ~/.ssh/{{ git_ssh_key }}