- name: Import zoom RPM key
  become: yes
  rpm_key:
    key: https://zoom.us/linux/download/pubkey?version=5-12-6
    
- name: Install zoom and enable repo
  become: yes
  package:
    name:
      - https://zoom.us/client/latest/zoom_x86_64.rpm